export const locations = [
  {
    id: 'fouesnant',
    name: 'Fouesnant',
    tideSite: 'concarneau',
    lat: 47.8904,
    lon: -4.0133,
    cameraIds: ['cap-coz', 'beg-meil', 'mousterlin', 'ile-saint-nicolas', 'port-la-foret'],
  },
  {
    id: 'loctudy',
    name: 'Loctudy',
    tideSite: 'concarneau',
    lat: 47.8272,
    lon: -4.1661,
    cameraIds: ['loctudy-perdrix'],
  },
  {
    id: 'guidel',
    name: 'Guidel',
    tideSite: 'lorient',
    lat: 47.7850,
    lon: -3.5256,
    cameraIds: ['guidel-port'],
  },
  {
    id: 'carnac',
    name: 'Carnac',
    tideSite: 'lorient',
    lat: 47.5835,
    lon: -3.0806,
    cameraIds: [
      'saint-colomban-panorama',
      'saint-colomban-vue2',
      'saint-colomban-pointe',
      'carnac-grande-plage',
    ],
  },
  {
    id: 'quiberon',
    name: 'Quiberon',
    tideSite: 'lorient',
    lat: 47.4860,
    lon: -3.1213,
    cameraIds: ['quiberon-grande-plage', 'quiberon-haliguen'],
  },
  {
    id: 'pornichet',
    name: 'Pornichet',
    tideSite: 'lecroisic',
    lat: 47.2645,
    lon: -2.3449,
    windguruStation: 5579,
    cameraIds: ['pornichet-plage', 'pornichet-surf'],
  },
]
